profiles:
  active:
  - dev
---
server:
  port: 81

spring:
  profiles: dev

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://129.211.74.18:7001/eureka/,http://129.211.74.18:7002/eureka/,http://129.211.74.18:7003/eureka/



feign:
  hystrix:
    enabled: true
