profiles:
  active:
  - dev
---
server:
  port: 89

spring:
  profiles: dev

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://129.211.74.18:7001/eureka/
      # defaultZone: http://129.211.74.18:7001/eureka/,http://129.211.74.18:7002/eureka/,http://129.211.74.18:7003/eureka/



feign:
  hystrix:
    enabled: true
