profiles:
  active:
  - dev
---

server:
  port: 8007

spring:
  profiles: dev
  application:
    name: microservicecloud-consumer
    
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://129.211.74.18:7001/eureka
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#
#
#
feign:
  hystrix:
    enabled: true
    
# hystrix:
#   command:
#     default:
#       execution:
#         isolation:
#           thread:
#             timeoutInMilliseconds: 500000
#       circuitBreaker:
#         sleepWindowInMilliseconds: 300000
#         forceClosed: true
        # 请求处理的超时时间  add by six-vision


        
ribbon:
  ReadTimeout: 300000
  SocketTimeout: 300000
  #请求连接的超时时间
  ConnectTimeout: 30000


feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
    time-to-live: 900

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: false

ribbon:
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  maxAutoRetries: 1
  eager-load:
    clients:
      - microservicecloud-student
      - microservicecloud-dormitory
  ConnectTimeout: 20000
  ReadTimeout: 20000